[book]
authors = ["Jacek Generowicz"]
language = "en"
multilingual = false
src = "src"
title = "Dataflow"

[output.html]
default-theme  = "ayu"
additional-css = ["mermaid.css"]
additional-js  = ["mermaid.min.js", "mermaid-init.js"]

[output.html.fold]
enable = true
level  = 3

[preprocessor.toc]
command = "mdbook-toc"

[preprocessor.mermaid]
command  = "mdbook-mermaid"
renderer = ["html"]
